name: nostr_dart
description: A Dart Library for making Nostr clients
version: 0.0.24
repository: https://github.com/ice-blockchain/nostr-dart

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  bip340: ^0.3.0
  crypto: ^3.0.6
  equatable: ^2.0.7
  web_socket_client: ^0.1.5

dev_dependencies:
  lint: ^2.3.0
  lints: ^2.0.0
  test: ^1.25.14
